# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_request', '0002_auto_20180307_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='productarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='featurereq',
            name='productarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feature_request.productarea'),
        ),
    ]
