# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_request', '0006_auto_20180308_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurereq',
            name='target_date',
            field=models.DateField(default='mm/dd/yyyy'),
        ),
    ]
