# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_request', '0007_auto_20180309_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurereq',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feature_request.Clients'),
        ),
    ]
